### PR TITLE
feat: add actions to fetch  self-serve settings

### PR DESCRIPTION
**Pull request by vladpoltorin**
## Why do we need this change?

A simple hook for fetching vendor's self-serve settings

### CODE REVIEW

**Review by salemhilal — APPROVED** [review]
Fix those type errors, but looks good to me otherwise!

**Comment by salemhilal** [comment]
what happens if I comment from Slack?

**Comment by salemhilal** [comment]
lol cool

**Comment by vladpoltorin** [comment]
Let me see how it works

**Comment by salemhilal** [comment]
"hey, I saw your PR exists but I didn't wanna click on it."

**Pull request merged**
